[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[fmt]
sort_imports = true
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
quote_style = "double"
tab_width = 4

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
